AWSTemplateFormatVersion: '2010-09-09'

Description: 'ssh key sample rest api - Account-level shared infrastructure'

Resources:
  # API Gateway
  APIGateway:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: 'ssh-key-rest'
      Description: 'SSH Key REST API'
  # SNS Topic for alerts
  AlertTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: 'Alerts'
  # CloudWatch Alarms for monitoring
  4XXErrorAlert:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: 'APIGateway-4XX-dev'
      AlarmDescription: '4xx Errors on API Gateway'
      ActionsEnabled: true
      AlarmActions:
        - !Ref 'AlertTopic'
      OKActions:
        - !Ref 'AlertTopic'
      Namespace: 'AWS/ApiGateway'
      MetricName: '4XXError'
      Dimensions:
        - Name: 'ApiName'
          Value: 'ssh-key-rest'
        - Name: 'Stage'
          Value: 'dev'
      EvaluationPeriods: 2
      Period: 60
      ComparisonOperator: 'GreaterThanThreshold'
      Threshold: 0
      Statistic: 'Maximum'
      TreatMissingData: 'notBreaching'
  5XXErrorAlert:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: 'APIGateway-5XX-dev'
      AlarmDescription: '5xx Errors on API Gateway'
      ActionsEnabled: true
      AlarmActions:
        - !Ref 'AlertTopic'
      OKActions:
        - !Ref 'AlertTopic'
      Namespace: 'AWS/ApiGateway'
      MetricName: '5XXError'
      Dimensions:
        - Name: 'ApiName'
          Value: 'ssh-key-rest'
        - Name: 'Stage'
          Value: 'dev'
      EvaluationPeriods: 2
      Period: 60
      ComparisonOperator: 'GreaterThanThreshold'
      Threshold: 0
      Statistic: 'Maximum'
      TreatMissingData: 'notBreaching'

Outputs:
  AlertTopicArn:
    Description: 'ARN of the SNS topic used for alerting'
    Value: !Ref 'AlertTopic'