AWSTemplateFormatVersion: '2010-09-09'

Description: 'ssh key sample rest api - Account-level shared infrastructure'

Resources:
  # CloudWatch Alarms for monitoring
  4XXErrorAlert:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: !If [ 'IsProduction', 'APIGateway-4XX-prod', 'APIGateway-4XX-dev' ]
      AlarmDescription: '4xx Errors on API Gateway'
      ActionsEnabled: true
      AlarmActions:
        - !Ref 'AlertTopic'
      OKActions:
        - !Ref 'AlertTopic'
      Namespace: 'AWS/ApiGateway'
      MetricName: '4XXError'
      Dimensions:
        - Name: 'ApiName'
          Value: 'rmsportal-api'
        - Name: 'Stage'
          Value: !If [ 'IsProduction', 'prod', 'dev' ]
      EvaluationPeriods: 2
      Period: 60
      ComparisonOperator: 'GreaterThanThreshold'
      Threshold: 0
      Statistic: 'Maximum'
      TreatMissingData: 'notBreaching'
  5XXErrorAlert:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: !If [ 'IsProduction', 'APIGateway-5XX-prod', 'APIGateway-5XX-dev' ]
      AlarmDescription: '5xx Errors on API Gateway'
      ActionsEnabled: true
      AlarmActions:
        - !Ref 'AlertTopic'
      OKActions:
        - !Ref 'AlertTopic'
      Namespace: 'AWS/ApiGateway'
      MetricName: '5XXError'
      Dimensions:
        - Name: 'ApiName'
          Value: 'rmsportal-api'
        - Name: 'Stage'
          Value: !If [ 'IsProduction', 'prod', 'dev' ]
      EvaluationPeriods: 2
      Period: 60
      ComparisonOperator: 'GreaterThanThreshold'
      Threshold: 0
      Statistic: 'Maximum'
      TreatMissingData: 'notBreaching