sudo: false
language: python
python: 3.6
cache: pip
jobs:
  include:
  - stage: test
    env: TOXENV=flake8
  - stage: test
    env: TOXENV=py36

stages:
- test

install:
- pip install -U setuptools pip
- pip install tox codecov

script: tox
after_success: codecov

env:
  global:
  - CODECOV_TOKEN=0d9db003-9cea-45c7-888c-b61aafe3fa0d